# Generated by Django 5.0 on 2025-08-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.UniqueConstraint(fields=('company', 'filleul'), name='uniq_referral_company_filleul'),
        ),
    ]
