# Generated by Django 5.0 on 2025-08-22 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reward',
            options={},
        ),
        migrations.AddField(
            model_name='reward',
            name='bucket',
            field=models.CharField(choices=[('SOUVENT', 'Souvent (~80/100)'), ('MOYEN', 'Moyen (~19/100)'), ('RARE', 'Rare (~1/100)'), ('TRES_RARE', 'Très rare (~1/10000)')], default='SOUVENT', max_length=10),
        ),
        migrations.AddField(
            model_name='reward',
            name='cooldown_days',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='reward',
            name='min_obtention',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='reward',
            name='weight',
            field=models.PositiveIntegerField(default=1, help_text='Poids relatif dans sa catégorie'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='channel',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reward',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='dashboard.client'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reward',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='label',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='reward',
            name='state',
            field=models.CharField(choices=[('PENDING', 'À envoyer'), ('SENT', 'Envoyé'), ('DISABLED', 'Désactivé'), ('ARCHIVED', 'Archivé')], default='PENDING', max_length=12),
        ),
    ]
