# Generated by Django 5.0 on 2025-08-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('dashboard', '0002_referral_uniq_referral_company_filleul'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='referral',
            name='uniq_referral_company_filleul',
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.UniqueConstraint(fields=('company', 'client'), name='uniq_referral_company_filleul'),
        ),
    ]
