# Generated by Django 5.0.14 on 2025-08-24 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_reward_options_reward_bucket_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='referral',
            name='uniq_referee_per_company',
        ),
    ]
