# Generated by Django 5.0 on 2025-08-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('dashboard', '0003_remove_referral_uniq_referral_company_filleul_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='referral',
            name='uniq_referral_company_filleul',
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.UniqueConstraint(fields=('company', 'referred'), name='uniq_referral_per_company_per_referred'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(check=models.Q(('referrer', models.F('referred')), _negated=True), name='referrer_not_equal_referred'),
        ),
    ]
