# Generated by Django 5.0.14 on 2025-08-25 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_company_delete_reward'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
