# Generated by Django 5.0 on 2025-08-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('dashboard', '0004_remove_referral_uniq_referral_company_filleul_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterModelOptions(
            name='referral',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='referral',
            name='uniq_referral_per_company_per_referred',
        ),
        migrations.RemoveConstraint(
            model_name='referral',
            name='referrer_not_equal_referred',
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('OK', 'Validé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.UniqueConstraint(fields=('company', 'referee'), name='uniq_referee_per_company'),
        ),
    ]
