# Generated by Django 5.0.14 on 2025-08-29 15:21

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('dashboard', '0005_delete_company'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('last_name'), django.db.models.functions.text.Lower('first_name'), models.F('company'), condition=models.Q(('is_referrer', True), models.Q(('last_name', ''), _negated=True)), name='uniq_referrer_name_per_company_ci'),
        ),
    ]
