# Generated by Django 5.0 on 2025-08-19 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_client_options_alter_referral_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='status',
        ),
    ]
