# Generated by Django 5.0 on 2025-08-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('dashboard', '0006_client_uniq_referrer_name_per_company_ci'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.UniqueConstraint(fields=('company', 'referee'), name='uniq_referee_per_company'),
        ),
    ]
