# Generated by Django 5.0 on 2025-09-08 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_referral_constraint_guard'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='referral',
            name='uniq_referee_per_company',
        ),
    ]
