# Generated by Django 5.0 on 2025-09-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('dashboard', '0009_remove_referral_uniq_referee_per_company'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.UniqueConstraint(fields=('company', 'referee'), name='uniq_referee_per_company'),
        ),
    ]
