# Generated by Django 5.0 on 2025-09-08 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_color',
            field=models.CharField(default='#ec4899', max_length=7, validators=[django.core.validators.RegexValidator(message='Couleur hex attendue, ex. #ec4899 ou #000', regex='^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$')]),
        ),
        migrations.AddField(
            model_name='company',
            name='secondary_color',
            field=models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator(message='Couleur hex attendue, ex. #ec4899 ou #000', regex='^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$')]),
        ),
        migrations.AddField(
            model_name='company',
            name='slogan',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, unique=True),
        ),
    ]
