# Generated by Django 4.2.25 on 2025-10-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(choices=[('superadmin', 'Superadmin (plateforme)'), ('admin', 'Admin d’entreprise'), ('operateur', 'Opérateur'), ('client', 'Client (V1: non utilisable)')], max_length=20),
        ),
    ]
