# Generated by Django 4.2.25 on 2025-10-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(choices=[('superadmin', 'Superadmin (plateforme)'), ('admin', 'Admin d’entreprise'), ('operateur', 'Opérateur')], max_length=20),
        ),
    ]
