# Generated by Django 5.0 on 2025-08-21 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbabilityWheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64)),
                ('pool', models.JSONField(default=list)),
                ('idx', models.PositiveIntegerField(default=0)),
                ('size', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probability_wheels', to='accounts.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'key'], name='rewards_pro_company_d89c95_idx')],
                'unique_together': {('company', 'key')},
            },
        ),
    ]
