# Generated by Django 4.2.25 on 2025-10-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='state',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Distrubué')], default='PENDING', max_length=20),
        ),
    ]
