# Generated by Django 5.0.14 on 2025-08-25 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('dashboard', '0005_delete_company'),
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('bucket', models.CharField(choices=[('SOUVENT', 'Souvent'), ('MOYEN', 'Moyen'), ('RARE', 'Rare'), ('TRES_RARE', 'Très rare')], max_length=20)),
                ('cooldown_days', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyée'), ('DISABLED', 'Désactivée'), ('ARCHIVED', 'Archivée')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='dashboard.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='accounts.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'client', 'state'], name='rewards_rew_company_675196_idx')],
            },
        ),
        migrations.CreateModel(
            name='RewardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(choices=[('SOUVENT', 'Souvent'), ('MOYEN', 'Moyen'), ('RARE', 'Rare'), ('TRES_RARE', 'Très rare')], max_length=10)),
                ('label', models.CharField(default='-10 % de remise', max_length=120)),
                ('cooldown_months', models.PositiveSmallIntegerField(default=1)),
                ('cooldown_days', models.PositiveIntegerField(default=30)),
                ('probability_display', models.CharField(default='', editable=False, max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_templates', to='accounts.company')),
            ],
            options={
                'ordering': ('company', 'bucket'),
                'unique_together': {('company', 'bucket')},
            },
        ),
    ]
