# Generated by Django 4.2.25 on 2026-04-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_alter_reward_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardtemplate',
            name='expires_at',
            field=models.DateField(blank=True, null=True, verbose_name='Date limite'),
        ),
        migrations.AddField(
            model_name='rewardtemplate',
            name='only_on_some_items',
            field=models.BooleanField(default=False, verbose_name='Valable sur certains articles'),
        ),
    ]
