# Generated by Django 5.0.14 on 2025-08-26 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('dashboard', '0005_delete_company'),
        ('rewards', '0002_reward_rewardtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='dashboard.referral'),
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.UniqueConstraint(fields=('company', 'client', 'referral'), name='uniq_reward_by_referrer_and_referral'),
        ),
    ]
