# Generated by Django 5.0.14 on 2025-08-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_reward_referral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='redeemed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='redeemed_channel',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reward',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
