# Generated by Django 5.0.14 on 2025-08-28 09:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0004_reward_redeemed_at_reward_redeemed_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
