# Generated by Django 5.0.14 on 2025-08-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0005_alter_reward_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
