# Generated by Django 5.0.14 on 2025-08-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0006_alter_reward_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardtemplate',
            name='min_referrals_required',
            field=models.PositiveIntegerField(default=0, help_text='Nombre minimum de parrainages requis pour débloquer cette récompense.'),
        ),
    ]
